name: getxtodo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  get: 4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  provider: ^6.0.2
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
